apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-apache
spec:
  replicas: 3
  selector:
    matchLabels:
      prod: apache
  template:
    metadata:
      labels:
        prod: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
