apiVersion: v1
kind: Pod
metadata:
  name: mysql
#  labels:
#    prod: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    imagePullPolicy: IfNotPresent
    envFrom:
      - configMapRef:
          name: mycf
      - secretRef:
          name: mypw
#    env:
#    - name: MYSQL_ROOT_PASSWORD
#      value: 12345!
#    - name: MYSQL_DATABASE
#      value: wordpress
    ports:
    - containerPort: 3306 
